In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe:

In [26]:
labels = pd.read_csv('labels.csv')

In [3]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

### Start with assessing the radiologist's performance:
* Assess the _accuracy_ of the radiologist by just looking at the percent of cases that they correctly labeled
* Next, look at the true positive and true negative rates of the radiologist by generating a _confusion matrix_ 

In [4]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [5]:
radiologist_accuracy

0.8993288590604027

In [6]:
confusion_matrix(labels.perfect_labeler.values,labels.radiologist.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

### Now look at the algorithm's performance compared to the perfect labeler:
* Since the algorithm doesn't create a binary label, it instead returns a _probability_ of cancer, choose a probability cut-off to use for the algorithm's labeling of cancer vs. bening. _(Hint: 0.5 is a reasonable starting place)_
* Start with assessing _accuracy_ again here
* Generate a confusion matrix

In [7]:
labels['algorithm_label'] = labels['algorithm'].apply(lambda x: 'cancer' if x >= 0.5 else 'benign')

In [8]:
labels.head(20)

perfect_labeler radiologist  algorithm algorithm_label
0           cancer      cancer       0.99          cancer
1           cancer      cancer       0.94          cancer
2           cancer      cancer       0.73          cancer
3           cancer      cancer       0.82          cancer
4           cancer      cancer       0.98          cancer
5           cancer      cancer       0.63          cancer
6           cancer      cancer       0.42          benign
7           cancer      cancer       0.99          cancer
8           cancer      cancer       0.92          cancer
9           cancer      cancer       0.45          benign
10          cancer      cancer       0.96          cancer
11          cancer      cancer       0.99          cancer
12          cancer      cancer       0.89          cancer
13          cancer      cancer       0.90          cancer
14          cancer      cancer       0.88          cancer
15          cancer      cancer       0.55          cancer
16          cancer      cancer       0.48          benign
17          cancer      cancer       0.77          cancer
18          cancer      cancer       0.67          cancer
19          cancer      cancer       0.37          benign

In [9]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.algorithm_label)/len(labels)

In [10]:
print(radiologist_accuracy)

0.8859060402684564


In [11]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_label.values,labels=["cancer","benign"])

array([[ 21,   8],
       [  9, 111]])

What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [19]:
labels['algorithm_label_04'] = labels['algorithm'].apply(lambda x: 'cancer' if x >= 0.4 else 'benign')

In [20]:
labels.head(10)

perfect_labeler radiologist  algorithm algorithm_label_04
0          cancer      cancer       0.99             cancer
1          cancer      cancer       0.94             cancer
2          cancer      cancer       0.73             cancer
3          cancer      cancer       0.82             cancer
4          cancer      cancer       0.98             cancer
5          cancer      cancer       0.63             cancer
6          cancer      cancer       0.42             cancer
7          cancer      cancer       0.99             cancer
8          cancer      cancer       0.92             cancer
9          cancer      cancer       0.45             cancer

In [21]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.algorithm_label_04)/len(labels)

In [22]:
print(radiologist_accuracy)

0.8590604026845637


In [23]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_label_04.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 17, 103]])

### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist. 

In [28]:
labels['algorithm_label'] = labels['algorithm'].apply(lambda x: 'cancer' if x >= 0.5 else 'benign')

In [29]:
labels.head(10)

perfect_labeler radiologist  algorithm algorithm_label
0          cancer      cancer       0.99          cancer
1          cancer      cancer       0.94          cancer
2          cancer      cancer       0.73          cancer
3          cancer      cancer       0.82          cancer
4          cancer      cancer       0.98          cancer
5          cancer      cancer       0.63          cancer
6          cancer      cancer       0.42          benign
7          cancer      cancer       0.99          cancer
8          cancer      cancer       0.92          cancer
9          cancer      cancer       0.45          benign

In [30]:
radiologist_accuracy = sum(labels.radiologist == labels.algorithm_label)/len(labels)

In [31]:
print(radiologist_accuracy)

0.8657718120805369


In [35]:
tn, fp, fn, tp = confusion_matrix(labels.perfect_labeler.values,labels.algorithm_label.values,labels=["cancer","benign"]).ravel()

In [36]:
print(tn, fp, fn, tp)

21 8 9 111


## Reflection: 
* In the above exercise you assess performances of a human as well as of an algorithm against a 'perfect labeler' and also against each other. 
* Does accuracy seem like the appropriate statistic to use when evaluating these labels? Why or why not? 
* In what clinical settings does it seem more or less acceptable to have a high level of FNs? FPs? 
* How did changing the threshold on the algorithm performance change the different performance statistics? 
* How did your opinion of the algorithm's performance change when you started comparing it to a radiologist instead of the perfect labeler? What does this mean for a real-world scenario when a perfect labeler doesn't exist, and we only have a radiologist's read to base our performance on? 